### ISSUE TITLE
How to disable Beagle at runtime?

### ISSUE THREAD

**Issue by Bajranghudda1** [pandulapeter/beagle#4]
I was looking for such a tool, it's too cool, you are really a cool dude. Thumbs up :+1: 
I got some issues when checked this - 

1. Not able to disable beagle using Beagle.isEnabled = false
2. Not able to achieve desired theme for buttons test style and fonts

**Comment by pandulapeter** [comment]
Hi! Thanks for the feedback, glad you like it :)

1. Bug! If you set isEnabled=false before the first Activity was created, indeed it didn't work. I've just released a fix, try it with version 1.2.1, it should be fine now.
2. Something fishy is going on with Buttons indeed... Take a look at the example app, there they are working. You can customize them by adding a "materialButtonStyle" (for Material theme) or a "buttonStyle" (AppCompat) attribute to your theme but I also found apps where this didn't work as expected. If they look really bad, my suggestion would be to set "shouldUseItemsInsteadOfButtons = true" in your [Appearance](https://github.com/pandulapeter/beagle/blob/master/beagle-core/src/main/java/com/pandulapeter/beagleCore/configuration/Appearance.kt) object until I manage to come up with a fix.

**Comment by Bajranghudda1** [comment]
Can't we disable it from a drawer just by using our Trick.Tuggle()?
I used this in a fragment but still not able to disable it

**Comment by pandulapeter** [comment]
Can't really reproduce your issue. All `Beagle.isEnabled` does is to lock the DrawerLayout so if it is `false`, you have no way of opening the drawer. I tried adding a Toggle widget like this:
`Trick.Toggle(
    title = "Enable Beagle",
    initialValue = Beagle.isEnabled,
    onValueChanged = { Beagle.isEnabled = it }
)`
By default the switch will be checked. The moment I uncheck it the drawer will be closed and there is no way to open it agan. Am I missing something?
